apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carin-pvc
  namespace: carin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi