apiVersion: v1
kind: Secret
metadata:
  name: yakle-secret
  namespace: yakle
type: Opaque
stringData:
  ALLOWED_ORIGINS: "https://yakle.sungju.xyz"
  SESSION_SECRET: "asdfawef-foiweaoew-aweifnawef-foiweaoew-aweifnawef"
  NODE_ENV: "production"