apiVersion: argoproj.io/v1alpha1
kind: Sensor

metadata:
  name: discord-sensor
  namespace: argo-events

spec:
  template:
    serviceAccountName: operate-workflow-sa

  dependencies:
  - name: webhook-dep
    eventSourceName: webhook
    eventName: incoming

  triggers:
  - template:
      name: discord-trigger

      argoWorkflow:
        operation: submit

        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow

            metadata:
              generateName: discord-

            spec:
              workflowTemplateRef:
                name: discord-message

              arguments:
                parameters:
                - name: message
                  value: placeholder

    parameters:
    - src:
        dependencyName: webhook-dep
        dataKey: body.message
      dest: spec.arguments.parameters.0.value
