apiVersion: v1
kind: Service
metadata:
  name: webhook-nodeport
  namespace: argo-events

spec:
  type: NodePort

  selector:
    eventsource-name: webhook

  ports:
  - name: webhook
    port: 12000
    targetPort: 12000
    nodePort: 31200
