apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dexam-be-dev-data
  namespace: dexam-be-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
